apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ske-operator
  namespace: kratix-platform-system
data:
  {{- with .Values.imageRegistry }}
  image-registry-host: {{ .host }}
  image-pull-secret: {{ .imagePullSecret | default "syntasso-registry" }}
  ske-platform-image: {{ .skePlatformImage.name }}
  ske-pipeline-image: {{ .skePlatformPipelineAdapterImage.name }}
  {{- end }}
  {{- with .Values.releasesBucket }}
  releases-bucket-name: {{ .name }}
  releases-bucket-path: {{ .path }}
  releases-bucket-region: {{ .region }}
  releases-bucket-endpoint: {{ .endpoint }}
  releases-bucket-secret-name: {{ .secretName}}
  {{- end }}
