
{{- if .Values.skeDeployment.enabled -}}
{{- with .Values.skeDeployment -}}
apiVersion: platform.syntasso.io/v1alpha1
kind: Kratix
metadata:
  name: kratix
spec:
  version: {{ .version | default "latest" }}
{{- end -}}
{{- end -}}