name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'kratix/**'

env:
  GITHUB_TOKEN: "${{ secrets.CR_TOKEN }}"
  CR_TOKEN: "${{ secrets.CR_TOKEN }}"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "syntassodev"
          git config user.email "kratix@syntasso.io"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Delete existing release/tag
        run: |
          gh release delete kratix-v0.0.1 -y --cleanup-tag || true

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          install_only: true

      - name: Package Chart
        run: |
          cr package kratix/

      - name: Upload Package
        run: |
          cr upload --owner syntasso --git-repo helm-charts --token $GITHUB_TOKEN --push

      - name: Update Index
        run: |
          git checkout gh-pages
          cr index --owner syntasso --git-repo helm-charts --index-path .
          yq -i '.entries.kratix |= [. | sort_by(.created) | .[-1]]' index.yaml
          git add index.yaml
          git commit -m "Update index.yaml"
          git push